# DON'T USE THIS ON PRODUCTION. It was designed for development only.
version: '3.4'
services:
  db-main:
    image: postgres:10
    container_name: ${ZTM_MAIN_DATABASE_CONTAINER}
    network_mode: ${ZTM_DOCKER_NETWORK}
  zcoind:
    image: zcoinofficial/zcoind:latest
    container_name: ${ZTM_ZCOIND_CONTAINER}
    network_mode: ${ZTM_DOCKER_NETWORK}
    command: -exodus -rpcallowip=0.0.0.0/0 -zmqpubhashblock=tcp://0.0.0.0:28332 ${ZTM_ZCOIND_PARAMS}
