// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ztm.Data.Entity.Postgres;

namespace Ztm.Data.Entity.Postgres.Migrations
{
    [DbContext(typeof(MainDatabase))]
    [Migration("20190502080045_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Ztm.Data.Entity.Contexts.Main.WebApiCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id");

                    b.Property<IPAddress>("RequestIp")
                        .IsRequired()
                        .HasColumnName("request_ip");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnName("request_time");

                    b.Property<byte[]>("TransactionId")
                        .HasConversion(new ValueConverter<byte[], byte[]>(v => default(byte[]), v => default(byte[]), new ConverterMappingHints(size: 32)))
                        .HasColumnName("transaction_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("webapi_callback_id_pkey");

                    b.HasIndex("TransactionId")
                        .HasName("webapi_callback_transaction_id_idx");

                    b.ToTable("webapi_callback");
                });
#pragma warning restore 612, 618
        }
    }
}
